### PR TITLE
merge envoy master

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by PiotrSikora** [comment]
We're switching to stable releases, so this is going to remain at 1.12.x for a while...

**Comment by lizan** [comment]
@PiotrSikora that's for the sha that istio-proxy pointing to right? it shouldn't block master?

**Comment by lizan** [comment]
will wait on #292

**Comment by jplevyak** [comment]
At this stage we do not want to be backporting and instead focus on upstreaming.

**Comment by rshriram** [comment]
How long is the upstreaming going to take? If its a few days, then okay. If it is anything more than that, then that doesn't work. Because the fix that lizan is trying to merge is a bug fix for Istio (about ALS metadata logging) as it is currently logging incorrect stuff.

**Comment by lizan** [comment]
@PiotrSikora @jplevyak I don't think we agreed locking down master to Envoy stable release, we agreed on locking down Istio release to Envoy stable release, to reduce maintenance cost.

**Comment by lizan** [comment]
If we think #297 is ok to cherry-pick the change for bug fix, I'm fine with that too. @rshriram @PiotrSikora

**Pull request closed without merging**
