### PR TITLE
Fix tests in previous commit.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]

**Comment by kyessenov** [comment]
I think the test is not cleaning up the stream. The assertion should be triggered.

**Comment by PiotrSikora** [comment]
Which assertion?

**Comment by kyessenov** [comment]
There's an assertion that responseCodeDetails are set.

**Comment by PiotrSikora** [comment]
Right, but in the previous commit you've added code to set responseCodeDetails if it's missing, so it's set now, isn't it?

**Comment by kyessenov** [comment]
Yes, it is set but it's not tested. I am just suggesting to fix the test and make it clean up explicitly, so that assertion is exercised. We wouldn't have the issue to begin with if the test was right.

**Comment by PiotrSikora** [comment]
I thought your code fixed issue in production and not tests?

**Comment by PiotrSikora** [comment]
I'm going to merge this to fix master, we can discuss proper fix later.

**Pull request merged**
