### PR TITLE
Sync to envoyproxy/envoy@6d816ad

### PR DESCRIPTION
**Pull request by diemtvu**
Sync to https://github.com/envoyproxy/envoy/commit/6d816ad9af0527e63ac58d0ffe7eac29bfe56d62

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by diemtvu** [comment]
@howardjohn @PiotrSikora Can you help merge this PR to envoy-wasm. Thanks.

**Comment by PiotrSikora** [comment]
Please roll-forward instead of cherry-picking.

**Comment by diemtvu** [comment]
> Please roll-forward instead of cherry-picking.

Can you suggest me a git command to do it properly? Thanks

**Comment by PiotrSikora** [comment]
Mostly [this](https://github.com/envoyproxy/envoy-wasm/pull/96#issuecomment-515717521), but you can skip the build container changes.

**Comment by diemtvu** [comment]
> Mostly [this](https://github.com/envoyproxy/envoy-wasm/pull/96#issuecomment-515717521), but you can skip the build container changes.

Done. PTAL

**Pull request merged**
