### PR TITLE
enable azp

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by lizan** [comment]
@yxue

**Comment by lizan** [comment]
@PiotrSikora the azp errors seems real and you'll likely see them when you make PR to upstream, I disabled WAVM so cmake shouldn't be the issue.

**Comment by PiotrSikora** [comment]
@lizan could you merge/rebase this on top of `master`?

**Comment by PiotrSikora** [comment]
Could you merge `master` to pick-up #238?

Also, on CircleCI we're only running Wasm tests, and not everything. You might want to do the same for Azure Pipelines.

**Pull request closed without merging**
