### PR TITLE
wasm: drop wasm_opt flag, it trips TSan and benefits are unclear.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by jplevyak** [comment]
What do you mean "benefits are unclear".

**Comment by PiotrSikora** [comment]
It enables _some_ optional optimizations in V8, but I couldn't see the difference in speed tests that we have.

**Comment by jplevyak** [comment]
Can we open an issue to do a fuller evaluation ?

LGTM

**Comment by PiotrSikora** [comment]
Done (#381)

**Pull request merged**
