### PR TITLE
Remove exception use in the WebAssembly VM.

### PR DESCRIPTION
**Pull request by jplevyak**
Signed-off-by: John Plevyak <jplevyak@gmail.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by jplevyak** [comment]
See https://github.com/envoyproxy/envoy-wasm/issues/9 for discussion.

**Comment by duderino** [comment]
Thanks for doing this @jplevyak.  Note to self: once it's merged, the wat/wasm files introduced in https://github.com/envoyproxy/envoy-wasm/pull/72 need to be rebuilt

**Comment by mandarjog** [comment]
@duderino please also indicate a GitHub “lgtm” not the bot stuff.
@jplevyak this is ready for you to merge.

**Pull request merged**
