### PR TITLE
stub out rust api wasm proxy callbacks

### PR DESCRIPTION
**Pull request by joshua-rutherford**
I'm looking to extend the Rust SDK but wanted to get these stubs in as I'm not sure the next time I'll be back here.  I am new to Rust so feeling my way out here a bit.  I've set up my tool chain to build with wasm-pack as the README.md was sparse on configuring the environment.  Is there some other tool chain recommended?

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Hi @joshua-rutherford!

We're using the regular Rust toolchain (`rustc`) and not `wasm-pack` / `wasm-bindgen`, since those are targeting browser environments, so your changes are partially wrong. I'll clean up the documentation, since it's indeed pretty useless right now.

I have the functions you provided working already, so I'd rather not merge empty stubs that will be changed soon... I'll try to commit what I have before the holidays, since it's been "stuck" in my local tree for way too long.

**Comment by joshua-rutherford** [comment]
Awesome, I'll hold off to see what you push.  Have you mirroring the C++ api to the extent possible.

**Comment by nilslice** [comment]
would love to follow the latest on the rust api stubs if not committed already. thanks!

**Comment by joshua-rutherford** [comment]
@PiotrSikora, I know you've probably been off for the holidays but wondering if you've got an update on pushing the latest?

**Pull request closed without merging**
