### PR TITLE
merge upstream/master to wasm

### PR DESCRIPTION
**Pull request by lizan**
Description:
This is currently blocking istio/istio from picking any upstream API changes because of config_dump protobuf changed.

Risk Level:
Testing:
Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by rshriram** [comment]
Thanks lizan!

**Comment by lizan** [comment]
Until here it is mostly mechanical + dedup + fix_format. I need more work to make CI pass.

**Comment by kyessenov** [comment]
Can we get this in? What's holding it?

**Comment by lizan** [comment]
@kyessenov someone has to approve, ping @PiotrSikora @jplevyak @htuch ?

**Comment by rshriram** [comment]
Ping!

**Pull request merged**
