### PR TITLE
Sync with master

### PR DESCRIPTION
**Pull request by venilnoronha**
/cc @PiotrSikora

### CODE REVIEW

**Comment by rshriram** [comment]
cc @lizan / @mandarjog [ we need this to fix the protocol sniffing issues]

**Comment by duderino** [comment]
@PiotrSikora

**Comment by PiotrSikora** [comment]
Interfaces changed, so this sync requires changes to WASM code as well.

**Comment by venilnoronha** [comment]
Okay, I'll update that.

**Comment by PiotrSikora** [comment]
I'm going to close this PR, since I'm going to be syncing with upstream once the the security release is out in a few hours.

**Pull request closed without merging**
