### PR TITLE
Sync with master (4fa3e9fae1).

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@bianpengyuan could you test your WASM extension against this PR? Thanks!

**Comment by bianpengyuan** [comment]
@PiotrSikora Sure, will let you know when I finish the test.

**Comment by PiotrSikora** [comment]
@bianpengyuan did you finish the test? :)

**Comment by bianpengyuan** [comment]
@PiotrSikora Yes just finished and found this bug: https://github.com/envoyproxy/envoy-wasm/pull/62 Everything else works fine.

**Pull request merged**
