### PR TITLE
Work around Envoy bug whereby the VM may die prematurely.

### PR DESCRIPTION
**Pull request by jplevyak**
Signed-off-by: John Plevyak <jplevyak@gmail.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
[2020-08-13 11:54:57.393][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[2020-08-13 11:54:57.393][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-08-13 11:54:57.393][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: 4182fbd338422cff592982a3108a6475f9344ec9/1.15.0/Modified/DEBUG/BoringSSL
[2020-08-13 11:54:57.456][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x55eb1e27d57c]
[2020-08-13 11:54:57.456][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1: __restore_rt [0x7fd08b1148a0]
[2020-08-13 11:54:57.515][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: tcmalloc::SLL_TryPop() [0x55eb1eed44bb]
[2020-08-13 11:54:57.575][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: tcmalloc::ThreadCache::FreeList::TryPop() [0x55eb1eed441f]
[2020-08-13 11:54:57.634][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: operator new[]() [0x55eb1efb48cc]
[2020-08-13 11:54:57.693][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: wasm::vec<>::deep_copy() [0x55eb1c5cdaab]
[2020-08-13 11:54:57.753][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: wasm::FuncType::copy() [0x55eb1c5cd630]
[2020-08-13 11:54:57.811][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: wasm::Func::make() [0x55eb1c5d13d1]
[2020-08-13 11:54:57.870][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: proxy_wasm::(anonymous namespace)::V8::registerHostFunctionImpl<>() [0x55eb1c589a73]
[2020-08-13 11:54:57.928][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: proxy_wasm::(anonymous namespace)::V8::registerCallback() [0x55eb1c578fd5]
[2020-08-13 11:54:57.987][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #10: proxy_wasm::WasmBase::registerCallbacks() [0x55eb1c561a3c]
[2020-08-13 11:54:58.045][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #11: Envoy::Extensions::Common::Wasm::Wasm::registerCallbacks() [0x55eb1c226c5f]
[2020-08-13 11:54:58.104][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #12: proxy_wasm::WasmBase::initialize() [0x55eb1c564fad]
[2020-08-13 11:54:58.162][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #13: proxy_wasm::createWasm() [0x55eb1c566274]
[2020-08-13 11:54:58.220][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #14: Envoy::Extensions::Common::Wasm::createWasmInternal()::$_6::operator()() [0x55eb1c22a0be]
[2020-08-13 11:54:58.277][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #15: Envoy::Extensions::Common::Wasm::createWasmInternal() [0x55eb1c228834]
[2020-08-13 11:54:58.335][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #16: Envoy::Extensions::Common::Wasm::createWasm() [0x55eb1c2273fc]
[2020-08-13 11:54:58.393][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #17: Envoy::Extensions::HttpFilters::Wasm::FilterConfig::FilterConfig() [0x55eb1b729b47]
[2020-08-13 11:54:58.451][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #18: __gnu_cxx::new_allocator<>::construct<>() [0x55eb1b725dc6]
[2020-08-13 11:54:58.509][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #19: std::allocator_traits<>::construct<>() [0x55eb1b725b52]
[2020-08-13 11:54:58.567][29786][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #20: std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>() [0x55eb1b7258a3]

**Comment by kyessenov** [comment]
Applying this patch to istio/envoy 1.7 causes a quick crash:
[2020-08-13 22:13:09.260][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[2020-08-13 22:13:09.260][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-08-13 22:13:09.260][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: e0cfec812e8a767b15d68fa8defaac03eb5aaae3/1.15.0/Modified/DEBUG/BoringSSL
[2020-08-13 22:13:09.318][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x55587b2fe5bc]
[2020-08-13 22:13:09.319][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1: __restore_rt [0x7f41d402d8a0]
[2020-08-13 22:13:09.377][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: tcmalloc::SLL_TryPop() [0x55587bf554fb]
[2020-08-13 22:13:09.434][32046][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: tcmalloc::ThreadCache::FreeList::TryPop() [0x55587bf5545f]
Segmentation fault

**Comment by JimmyCYJ** [comment]
Is there a tracking issue for this PR? What is the priority of the issue?

**Comment by PiotrSikora** [comment]
What's the status of this PR? Did you test the latest commit, @kyessenov?

**Comment by kyessenov** [comment]
I tested last time and it was still crashing.
In general, we can't just skip log() calls. They are used for audit logging, so cannot be dropped.

**Pull request closed without merging**
