### PR TITLE
Sync with master (e61681d)

### PR DESCRIPTION
**Pull request by Monkeyanator**
Bring in latest commits from envoyproxy/envoy

### CODE REVIEW

**Comment by silentdai** [comment]
@Monkeyanator need "Config Dump for Secret Discovery Service. (#7365)"
@PiotrSikora What is the instruction to sync with envoy upstream? Is it 
rebase followed by push to master?

**Comment by Monkeyanator** [comment]
@silentdai I believe "Config Dump for Secret Discovery Service. (#7365)" is included in the seven being merged here

**Comment by PiotrSikora** [comment]
@silentdai 
```
$ git fetch origin # https://github.com/envoyproxy/envoy
$ git fetch envoy-wasm # https://github.com/envoyproxy/envoy-wasm
$ git checkout -b wasm-sync origin/master
$ git merge envoy-wasm/master
# resolve all merge conflicts - this requires knowledge about changes on both sides
$ vim ...
$ git add ...
$ bazel build --define wasm=enabled //source/exe:envoy-static
$ bazel test  --define wasm=enabled //test/...
$ git commit -s
$ cd ci/build_container
# clear cached Docker images
$ for i in `docker images -q`; do docker rmi -f $i; done
$ export LINUX_DISTRO=ubuntu
$ export IMAGE_NAME=USERNAME/envoy
$ export CIRCLE_SHA1=`git rev-parse HEAD`
$ ./docker_build.sh
$ docker push $IMAGE_NAME:$CIRCLE_SHA1
# update build image with $CIRCLE_SHA1
$ vim .circleci/config.yml
$ git commit -s -m "ci: update build image." .circleci/config.yml
$ git push USERNAME-wasm wasm-sync
# open draft pull request on GitHub
# wait until all tests on CircleCI pass (ignore DCO failure)
# push directly to master to avoid squashing history
$ git push envoy-wasm wasm-sync:master
```

**Comment by PiotrSikora** [comment]
Per chat with @Monkeyanator, superseded by #101.

**Pull request closed without merging**
