### PR TITLE
Update protobuf to v3.9.1.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Built using:

   git clone https://github.com/protocolbuffers/protobuf
   cd protobuf
   git checkout v3.9.1
   git clone https://github.com/kwonoj/protobuf-wasm patches
   git apply patches/*.patch
   sh autogen.sh
   emconfigure ./configure CXXFLAGS="-O3"
   emmake make

with Emscripten 1.38.46 (fastcomp).

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@jplevyak since `.wasm` files are built using 1.38.46, 1 test is broken under WAVM (see: #213), but we don't exercise tests under WAVM on the CI... Let me know if you prefer that I regenerate everything using 1.38.45, where everything works.

**Comment by jplevyak** [comment]
Yes, please regerate so that WAVM is not broken.  I am trying to find the problem.

**Comment by jplevyak** [comment]
Did the image work?  I am concerned that the protobuf patch doesn't work cleanly (I have had problems with it before).

**Comment by PiotrSikora** [comment]
Regenerated everything with Emscripten 1.38.45 (fastcomp).

**Comment by PiotrSikora** [comment]
> Yes, please regerate so that WAVM is not broken. I am trying to find the problem.

Done.

> Did the image work? I am concerned that the protobuf patch doesn't work cleanly (I have had problems with it before).

I didn't use any image. I only updated the Emscripten version number there.

**Comment by jplevyak** [comment]
Could you test the resulting image?

**Comment by PiotrSikora** [comment]
Switched back to 1.38.46, since all tests pass with WAVM now.

The Docker image built fine, and I verified that it can regenerate `.wasm` files using scripts provided in #210.

**Pull request merged**
