### PR TITLE
bump re2 for wasm build

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by jplevyak** [comment]
AFAICT, the version we have is the same version that is in envoyproxy/envoy upstream .  If this is important shouldn't it be upstreamed?  I don't mind putting this in early here but please attach a pointer to the upstream PR to get it into envoyproxy/envoy because when we upstream this will go away otherwise.

**Comment by Shikugawa** [comment]
@jplevyak This PR had been already merged. So you don't have to worry about it. https://github.com/envoyproxy/envoy/commit/8fd1a52e608f7223b4864ca913cc3ed82340991d

**Comment by Shikugawa** [comment]
@jplevyak Definitely. We don't have to create bump PR for only envoy-wasm. To avoid dup, I will create this PR on upstream envoyproxy/envoy.

**Comment by Shikugawa** [comment]
This PR may not be needed anymore.

**Comment by Shikugawa** [comment]
https://github.com/envoyproxy/envoy/pull/11669

**Pull request closed without merging**
