### PR TITLE
fix: support `log()` in the context of `Access Logger` extensions

### LINKED ISSUE #487: Envoy crashes on attempt to use `envoy.access_loggers.wasm` extension
*Title*: Envoy crashes on attempt to use `envoy.access_loggers.wasm` extension

*Probable cause*:
* `envoy.access_loggers.wasm` calls `log(..)` method on the `Root Context`
* [implementation](https://github.com/envoyproxy/envoy-wasm/blob/master/source/extensions/common/wasm/context.cc#L1414-L1433) of `log(..)` calls both `onLog()` and `onDelete()`
* `Root Context` of an Access Logger must be destroyed after the first use

*Repro steps*:
* Use `envoy.access_loggers.wasm` implementation from this repo ([test/extensions/access_loggers/wasm/test_data/logging.wasm](https://github.com/envoyproxy/envoy-wasm/blob/master/test/extensions/access_loggers/wasm/test_data/logging.wasm))
* Use the following Envoy config
  ```yaml
  admin:
    access_log_path: "/dev/null"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9901
  
  static_resources:
    listeners:
    - name: ingress
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
      - filters:            
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: mock_service
            http_filters:
            - name: envoy.router
              config: {}
            access_log:
            - name: envoy.access_loggers.wasm
              typed_config:
                "@type": type.googleapis.com/envoy.config.accesslog.v2.WasmAccessLog      
                config:
                  name: "access-logger"
                  vm_config:
                    vm_id: "vm-with-access-logger"
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      local:
                        filename: /etc/envoy/logging.wasm
  
    - name: mock
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 10001
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            stat_prefix: mock
            route_config:
              name: local_route
              virtual_hosts:
              - name: mock
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  direct_response:
                    status: 200
                    body:
                      inline_string: "Hi from mock service!\n"
            http_filters:
            - name: envoy.router
              config: {}
  
    clusters:
    - name: mock_service
      connect_timeout: 0.25s
      type: static
      lb_policy: round_robin
      hosts:
      - socket_address:
          address: 127.0.0.1
          port_value: 10001
  ```
* Make a test request 
  ```shell
  curl -i localhost:10000 
  ```
  Envoy will crash after that

*Call Stack*:
```
envoy_1  | [2020-04-21 08:18:02.224][17][debug][wasm] [bazel-out/k8-opt/bin/source/extensions/common/wasm/_virtual_includes/wasm_hdr/extensions/common/wasm/wasm_vm.h:50] WasmVm created envoy.wasm.runtime.v8 now active
envoy_1  | [2020-04-21 08:18:02.229][17][debug][wasm] [source/extensions/common/wasm/wasm.cc:93] Thread-Local Wasm created 3 now active
envoy_1  | [2020-04-21 08:18:06.770][17][critical][main] [source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
envoy_1  | [2020-04-21 08:18:06.770][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
envoy_1  | [2020-04-21 08:18:06.770][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: f80bba648062e95b98497b84ba20a8165828b082/1.15.0-dev/Clean/RELEASE/BoringSSL
envoy_1  | [2020-04-21 08:18:06.787][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x55ef42eb4484]
envoy_1  | [2020-04-21 08:18:06.798][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #1: [0x55ef42eb4399]
envoy_1  | [2020-04-21 08:18:06.809][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: std::__terminate() [0x55ef43470c93]
envoy_1  | [2020-04-21 08:18:06.819][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream() [0x55ef42c68e35]
envoy_1  | [2020-04-21 08:18:06.828][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x55ef429fd3d3]
envoy_1  | [2020-04-21 08:18:06.837][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: event_process_active_single_queue [0x55ef42e47826]
envoy_1  | [2020-04-21 08:18:06.846][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: event_base_loop [0x55ef42e463ae]
envoy_1  | [2020-04-21 08:18:06.855][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: Envoy::Server::WorkerImpl::threadRoutine() [0x55ef429f2eb4]
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x55ef42eea573]
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: start_thread [0x7f4142c236ba]
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x1
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: f80bba648062e95b98497b84ba20a8165828b082/1.15.0-dev/Clean/RELEASE/BoringSSL
envoy_1  | [2020-04-21 08:18:06.863][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: __restore_rt [0x7f4142c2d390]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #1: [0x55ef42eb4399]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: std::__terminate() [0x55ef43470c93]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream() [0x55ef42c68e35]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x55ef429fd3d3]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: event_process_active_single_queue [0x55ef42e47826]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: event_base_loop [0x55ef42e463ae]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: Envoy::Server::WorkerImpl::threadRoutine() [0x55ef429f2eb4]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x55ef42eea573]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: start_thread [0x7f4142c236ba]
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: f80bba648062e95b98497b84ba20a8165828b082/1.15.0-dev/Clean/RELEASE/BoringSSL
envoy_1  | [2020-04-21 08:18:06.872][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: __restore_rt [0x7f4142c2d390]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #1: [0x55ef42eb4399]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: std::__terminate() [0x55ef43470c93]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream() [0x55ef42c68e35]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x55ef429fd3d3]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: event_process_active_single_queue [0x55ef42e47826]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: event_base_loop [0x55ef42e463ae]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: Envoy::Server::WorkerImpl::threadRoutine() [0x55ef429f2eb4]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x55ef42eea573]
envoy_1  | [2020-04-21 08:18:06.880][17][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: start_thread [0x7f4142c236ba]
```

Reproducible on:
* `53d86e619`
* `d29f7a659`

### PR DESCRIPTION
**Pull request by yskopets**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message: support `log()` in the context of `Access Logger` extensions
Additional Description: make it possible to use `Access Logger` extensions
Risk Level: Low
Testing: unit tests, manual testing
Docs Changes: N/A
Release Notes: N/A
[Optional Runtime guard:]
Fixes: #487
[Optional Deprecated:]

### CODE REVIEW

**Comment by jplevyak** [comment]
Can we pull this into master then backport it.  Master has diverged.  Also, v1.15 isn't used by istio which is using istio/envoy @ release-1.7.  Also, can we add a test to demonstrate this.   If you don't want to do that I can take this over for master.  Up to you.

**Comment by yskopets** [comment]
@jplevyak Sure, I will rebase this PR against `master` and add some tests.

**Comment by jplevyak** [comment]
For master I think you can just do:
  +  if (!isRootContext()) {
  +    // For HTTP stream contexts, log() is last call in the Envoy lifecycle.
  +    onDelete();
  +  }

For the test you can use the WasmTestBase in test/test_common/wasm_base.h which should make it relatively straightfoward.

**Comment by yskopets** [comment]
@jplevyak Please take another look.

Notice that I wasn't able to create a test for an `Access Log` extension in `C++` since `proxy-wasm-cpp-sdk` and `NullVM` don't support dispatching `proxy_on_log` callback into a root context.

[test/extensions/access_loggers/wasm/test_data/test_cpp.cc]() is not used right now and, overall, is not representative for `envoy.access_loggers.wasm` extensions.

**Comment by jplevyak** [comment]
See https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/55

We need to move the onLog to ContextBase since AccessLog plugins call directly on the Root Context.

**Comment by jplevyak** [comment]
https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/58

This is necessary to get the Null VM tests working.

I have a different test upstream for coverage but I will merge your changes before reimporting to this repo.

**Pull request closed without merging**
