### PR TITLE
Update validation in Inline DNS table (#11897)

### PR DESCRIPTION
**Pull request by lambdai**
Signed-off-by: Shriram Rajagopalan <rshriram@tetrate.io>
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

### CODE REVIEW

**Comment by lambdai** [comment]
CC @rshriram

**Comment by lambdai** [comment]
@jplevyak This is a important fix. We want it in istio proxy 1.7

**Comment by lizan** [comment]
Aren't we going to backport in envoyproxy/envoy?

**Comment by lambdai** [comment]
@lizan  Absolutely. Let me complete the istio follow up...

**Comment by PiotrSikora** [comment]
Shouldn't this be backported to `envoy-wasm:release/v1.15` and `istio/envoy:release-1.7` as well?

**Pull request merged**
