### PR TITLE
update createStatsSink to use ServerFactoryContext

### PR DESCRIPTION
**Pull request by Aakash2017**
Signed-off-by: Aakash Shukla <aakashshukla@google.com>

Commit Message: updated creatStatSink function to take in Server::Configuration::ServerFactoryContext as a parameter instead of Server::Instance.
Additional Description: This change is necessary for wasm-stat-sink endpoint (https://github.com/envoyproxy/envoy-wasm/pull/566), since the createWasm call needed to instantiate the wasm endpoint requires FactoryContext object methods (such as but not limited to ClusterManager() and scope()).
Risk Level: Low

### CODE REVIEW

**Comment by jplevyak** [comment]
@lizan should we do this first in envoy-wasm then backport to envoyproxy?

**Comment by Aakash2017** [comment]
ping @lizan

**Comment by lizan** [comment]
Let's do this in envoyproxy/envoy first.

**Comment by Aakash2017** [comment]
the corresponding pr has been merged in envoy-proxy/envoy https://github.com/envoyproxy/envoy/commit/755dfe0fda2b1395441924b390c3fd605502e447

**Comment by PiotrSikora** [comment]
We need to pull envoyproxy/envoy@755dfe0 in a merge from `envoyproxy/envoy:master`.

Please coordinate with @richardwxn (see: #593) to avoid duplicating work.

**Comment by PiotrSikora** [comment]
(@jplevyak is working on the merge)

**Pull request closed without merging**
